### ISSUE TITLE
Italic text appears plain in the reply indicator

### ISSUE THREAD

**Issue by ljcooke** [hometown-fork/hometown#1319]
### Steps to reproduce the problem

1. Find a post with italic text. Example: https://toot.cat/@dredmorbius/110669659400644667
2. Click the reply button.

### Expected behaviour

The content above the compose form looks identical to the post in the timeline

### Actual behaviour

The content above the compose form is unstyled

### Detailed description

The HTML in the "reply indicator" is the same as the original post, but any italic text appears plain here.

**Likely cause**: `<div class="reply-indicator__content">` doesn't match the CSS selector, which expects an additional `<div class="status__content__text">` around the post content.

```html
<!-- HTML in timeline -->
<div class="status__content status__content--with-action" tabindex="0">
  <div class="status__content__text status__content__text--visible translate">
    <p>Hello <em>world</em></p>
  </div>
</div>

<!-- HTML above the compose form -->
<div class="reply-indicator__content translate">
  <p>Hello <em>world</em></p>
</div>
```

```css
.reply-indicator__content .status__content__text em,
.reply-indicator__content .status__content__text i,
.status__content .status__content__text em,
.status__content .status__content__text i {
  font-style: italic;
}
```

### Specifications

Hometown v4.0.5+hometown-1.1.1
